### ISSUE TITLE
How can I better understand computational geometry?

### ISSUE THREAD

**Issue by jrzimmerman** [tmcw/ama#5]
From reading a lot of the turf codebase, I can safely assume that you're knowledgable in computational geometry. What are some resources that helped you in the past to better understand and apply this to your projects?

**Comment by tmcw** [comment]
There are a bunch of true computational geometry wizards on the Mapbox team, like Ansis and Konstantin - I wouldn't claim to be on that level. There's a pretty big gap between being able to implement someone's thesis in code and actually writing the thesis :)

I basically started relearning math in 2011, with [the first running map I made](http://www.macwright.org/2011/07/28/mapping-runs.html): something as simple as atan2 was super cool to rediscover, and from there you acquire a sort of intuitive understanding of what the trig functions will do, how radians, degrees, intervals work.

That stuff, the core, is really vital to any kind of progress, and it's usually all I can remember offhand.

I've also learned from reading code like [pre3d](https://github.com/deanm/pre3d/tree/master), reading the [internals of d3](https://github.com/mbostock/d3), and playing a lot in environments that give you quick visual feedback, like [processing](https://processing.org/) and [tributary.io](http://tributary.io/).

Math wikipedia is a travesty: for really basic math concepts you can occasionally find a good page, but beyond that it becomes insidery gibberish written by people who couldn't explain addition. [MathWorld](http://mathworld.wolfram.com/) is usually better, and [Khan Academy](https://www.khanacademy.org/) is also pretty good if you want to learn a subject area.

There's a big gap between knowing something temporarily and crystallizing knowledge into something you can use everyday. The main ingredient is time and repetition but you can speed it up by teaching - writing [math for pictures](http://www.macwright.org/2013/03/05/math-for-pictures.html) helped a lot with really nailing down those concepts for me.

**Comment by jrzimmerman** [comment]
Great response @tmcw! Thanks for the answer and I'll definitely look at these resources!
